trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'Install dependencies'

- script: npm test
  displayName: 'Run linting'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/my-node-app.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'my-node-app'
    targetPath: '$(Build.ArtifactStagingDirectory)/my-node-app.zip'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'My-Azure-Subscription'
    appName: 'My-Sample-App'
    package: '$(Pipeline.Workspace)/drop/my-node-app/my-node-app.zip'
